# Generated by Django 4.1.5 on 2024-02-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('county', models.CharField(max_length=25)),
                ('primary', models.IntegerField()),
                ('post_primary', models.IntegerField()),
                ('special', models.IntegerField()),
            ],
        ),
    ]
