# Generated by Django 4.1.5 on 2024-02-06 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post_Primary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
                ('address', models.TextField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.county')),
            ],
        ),
        migrations.CreateModel(
            name='Primary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
                ('address', models.TextField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.county')),
            ],
        ),
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
                ('address', models.TextField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.county')),
            ],
        ),
        migrations.DeleteModel(
            name='Schools',
        ),
    ]
