# Generated by Django 4.1.5 on 2024-02-08 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_transport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='bus',
            field=models.CharField(max_length=10),
        ),
    ]
