# Generated by Django 4.1.5 on 2024-02-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_alter_transport_bus'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('area', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
