# Generated by Django 4.1.5 on 2024-02-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.CharField(max_length=50),
        ),
    ]
