# Generated by Django 4.1.5 on 2024-02-12 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_alter_house_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra_Transport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bus', models.CharField(max_length=10)),
                ('route_from', models.CharField(max_length=100)),
                ('route_to', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='transport',
            name='county',
            field=models.CharField(default='Dublin', max_length=50),
        ),
    ]
